In [25]:
from bs4 import BeautifulSoup
from selenium import webdriver
import time
import pandas as pd

In [48]:
url = "https://www.instahyre.com/search-jobs?company_size=0&isLandingPage=true&job_type=0&location=Anywhere+in+India&search=true"
driver = webdriver.Chrome()
driver.get(url)
time.sleep(5)

In [42]:
data = []
a = 30
while (a>0):
    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")
    view_link_div = soup.find_all('div',class_='opportunity-action-links')
    for i in view_link_div:
        link = i.find('a',href=True)
        driver.get(link['href'])
        time.sleep(2)
        s_page = BeautifulSoup(driver.page_source,"html.parser")
        c_info = s_page.find('div',class_='company-info')
        company_name = s_page.find('h2',class_='company-name').text
        div_info = c_info.find_all('div')
        f_year = div_info[0].text
        n_employee = div_info[1].text
        
        location = s_page.find('div',class_ = 'job-locations').find_all('span')[0].text
        designation = s_page.find('div',class_='profile-info').find('h1').text
        hr_name = s_page.find('span',class_='rec-name').text
        try:
            skills =','.join([x.text for x in  s_page.find('ul',{'id':'job-skills-description'}).find_all('li')])
        except:
            print(str(a)+' / '+company_name)
        data.append([company_name,f_year,n_employee,location,designation,hr_name,skills])
        driver.execute_script('history.back()')
        time.sleep(1)
        
    
    driver.execute_script('$(".pagination li:last").click()')
    time.sleep(3)
    a-=1

25 / MyBillBook (FloBiz)
22 / Acko
22 / Acko
21 / Acko
21 / Acko
20 / Acko
20 / Acko
4 / 314e Corporation

In [43]:
df = pd.DataFrame(data , columns = ['name','estab_year','employees_count','location','designation','hr_name','skills'])

In [44]:
df.to_csv('C:\\Users\\User\\Desktop\\company.csv')

In [45]:
df

,name,estab_year,employees_count,location,designation,hr_name,skills
0,FalconX,Founded in 2018,50 - 200 employees,Bangalore,Finance Associate Controller (Drive),Divya Kasula,"Chartered Accountant,IFRS,Legal Compliance,Sta..."
1,FalconX,Founded in 2018,50 - 200 employees,Bangalore,Finance Associate Reporting (Drive),Divya Kasula,"Chartered Accountant,Financial Reporting,Liqui..."
2,goGlocal,Founded in 2021,10 - 50 employees,Mumbai,BDE / BDA - Inside Sales (Drive),Kreesha Shah,"Lead Generation,Sales"
3,IDfy,Founded in 2011,200 - 500 employees,Mumbai,Key Account Manager (Drive),Stuti Srivastava,"Business Development,Key Account Management,Le..."
4,Indium Software,Founded in 1999,More than 1000 employees,"Bangalore, Hyderabad",Data Analyst / Senior Data Analyst (Drive),Mohamed Aslam,"NumPy,Power BI,Python,R,SQL,Tableau,pandas"
...,...,...,...,...,...,...,...
335,Splore,Founded in 2023,10 - 50 employees,Bangalore,Engineering Manager,Krishanu B,AWS
336,Synaptic,Founded in 2016,50 - 200 employees,Gurgaon,DevOps / Site Reliability - Staff Engineer,Rohit Gupta,"AWS,Kubernetes,DevOps,Big Data,Docker"
337,Synaptic,Founded in 2016,50 - 200 employees,Gurgaon,SDE III - Frontend,Rohit Gupta,"React.js,JavaScript,React Native,CI - CD,Highc..."
338,Synaptic,Founded in 2016,50 - 200 employees,Gurgaon,Site Reliability Engineer - SDE III,Rohit Gupta,"AWS,Kubernetes,CI - CD,Big Data,Docker"
339,Synaptic,Founded in 2016,50 - 200 employees,Gurgaon,Staff Engineer - Frontend,Rohit Gupta,"React.js,JavaScript,React Native,CI - CD,Unit ..."